extends Node
## Music director. Every Risk Zone gets its own theme (GAME_DESIGN.md §12, §21).
## Tracks are 8-bit chiptune loops generated by tools/generate_music.py —
## two pulse channels, a triangle bass and an LFSR noise channel, same as an NES.
##
## Two players crossfade so room transitions never cut the music dead.

const MUSIC_DIR := "res://assets/audio/music/"
const FADE_TIME := 0.7
const SILENT_DB := -60.0
## At high Risk the track plays a touch sharp and faster. It is the cheapest
## honest way to get §21's "high-risk variation" without five more tracks.
const HIGH_RISK_THRESHOLD := 0.5
const HIGH_RISK_PITCH := 1.06

const VICTORY_CUE := "claim_victory"

var volume: float = 0.7
var enabled: bool = true

var _players: Array[AudioStreamPlayer] = []
var _active: int = 0
var _current: String = ""
var _fade: Tween


func _ready() -> void:
	# Keep playing while the tree is paused so the pause menu is not silent.
	process_mode = Node.PROCESS_MODE_ALWAYS
	for i in 2:
		var player := AudioStreamPlayer.new()
		player.process_mode = Node.PROCESS_MODE_ALWAYS
		player.volume_db = SILENT_DB
		add_child(player)
		_players.append(player)

	var settings: Dictionary = SaveManager.get_section("settings")
	volume = clampf(float(settings.get("music_volume", 0.7)), 0.0, 1.0)
	enabled = bool(settings.get("music_enabled", true))

	Events.room_started.connect(_on_room_started)
	Events.risk_changed.connect(_on_risk_changed)
	Events.run_ended.connect(_on_run_ended)


func _on_room_started(path: String) -> void:
	play(String(LevelData.entry(path).get("music", "blaze_borough")))


func _on_risk_changed(value: float) -> void:
	var pitch := HIGH_RISK_PITCH if value >= HIGH_RISK_THRESHOLD else 1.0
	for player in _players:
		player.pitch_scale = pitch


func _on_run_ended(_report: Dictionary) -> void:
	play(VICTORY_CUE, false)


func play(track: String, loop: bool = true) -> void:
	if track == _current:
		return
	var stream := _load_track(track, loop)
	if stream == null:
		return
	_current = track

	var incoming: AudioStreamPlayer = _players[1 - _active]
	var outgoing: AudioStreamPlayer = _players[_active]
	_active = 1 - _active

	incoming.stream = stream
	incoming.pitch_scale = HIGH_RISK_PITCH if GameManager.risk >= HIGH_RISK_THRESHOLD else 1.0
	incoming.volume_db = SILENT_DB
	incoming.play()

	if _fade != null and _fade.is_valid():
		_fade.kill()
	_fade = create_tween()
	_fade.set_parallel(true)
	_fade.tween_property(incoming, "volume_db", _target_db(), FADE_TIME)
	_fade.tween_property(outgoing, "volume_db", SILENT_DB, FADE_TIME)
	_fade.set_parallel(false)
	_fade.tween_callback(outgoing.stop)


func set_volume(value: float) -> void:
	volume = clampf(value, 0.0, 1.0)
	_apply_volume()
	_save()


func set_enabled(value: bool) -> void:
	enabled = value
	_apply_volume()
	_save()


func toggle() -> bool:
	set_enabled(not enabled)
	return enabled


func _apply_volume() -> void:
	if _fade != null and _fade.is_valid():
		_fade.kill()
	_players[_active].volume_db = _target_db()
	_players[1 - _active].volume_db = SILENT_DB


func _target_db() -> float:
	if not enabled or volume <= 0.001:
		return SILENT_DB
	return linear_to_db(volume)


func _save() -> void:
	var settings: Dictionary = SaveManager.get_section("settings")
	settings["music_volume"] = volume
	settings["music_enabled"] = enabled
	SaveManager.set_section("settings", settings)


func _load_track(track: String, loop: bool) -> AudioStreamWAV:
	var path := MUSIC_DIR + track + ".wav"
	if not ResourceLoader.exists(path):
		push_warning("MusicManager: missing track %s" % path)
		return null
	var stream: AudioStreamWAV = load(path)
	if stream == null:
		return null
	# The WAV importer defaults to no looping, so set it here rather than
	# depending on hand-written .import files staying in sync.
	if loop:
		stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
		stream.loop_begin = 0
		stream.loop_end = _frame_count(stream)
	else:
		stream.loop_mode = AudioStreamWAV.LOOP_DISABLED
	return stream


func _frame_count(stream: AudioStreamWAV) -> int:
	var bytes_per_sample := 1 if stream.format == AudioStreamWAV.FORMAT_8_BITS else 2
	var channels := 2 if stream.stereo else 1
	return stream.data.size() / (bytes_per_sample * channels)
