extends Node
## Sound effects. 8-bit one-shots generated by tools/generate_sfx.py, played
## through a small pool so rapid fire never cuts itself off (GAME_DESIGN.md §21).
##
## Three guards keep it from turning to mush:
##   - a pool, so a new sound never stops the previous one
##   - a per-sound retrigger window, so one event firing twice in a frame
##     does not stack into clipping
##   - pitch jitter, so repeated sounds do not fatigue the ear

const SFX_DIR := "res://assets/audio/sfx/"
const POOL_SIZE := 14
const RETRIGGER_GUARD := 0.035
const CHAIN_WINDOW := 0.9
const CHAIN_MAX_STEPS := 12

var volume: float = 0.8
var enabled: bool = true

var _players: Array[AudioStreamPlayer] = []
var _next: int = 0
var _cache: Dictionary = {}
var _last_played: Dictionary = {}
var _chain_count: Dictionary = {}
var _chain_time: Dictionary = {}


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for i in POOL_SIZE:
		var player := AudioStreamPlayer.new()
		player.process_mode = Node.PROCESS_MODE_ALWAYS
		add_child(player)
		_players.append(player)

	var settings: Dictionary = SaveManager.get_section("settings")
	volume = clampf(float(settings.get("sfx_volume", 0.8)), 0.0, 1.0)
	enabled = bool(settings.get("sfx_enabled", true))


func play(sound: String, jitter: float = 0.06, volume_scale: float = 1.0) -> void:
	_emit(sound, 1.0 + randf_range(-jitter, jitter), volume_scale)


## Each call within CHAIN_WINDOW plays a semitone higher — coin runs and
## takedown streaks climb instead of repeating flatly.
func play_chain(sound: String, volume_scale: float = 1.0) -> void:
	var now := _now()
	if now - float(_chain_time.get(sound, -99.0)) > CHAIN_WINDOW:
		_chain_count[sound] = 0
	_chain_time[sound] = now
	var steps: int = mini(int(_chain_count.get(sound, 0)), CHAIN_MAX_STEPS)
	_chain_count[sound] = steps + 1
	_emit(sound, pow(2.0, steps / 12.0), volume_scale)


func play_pitched(sound: String, semitones: float, volume_scale: float = 1.0) -> void:
	_emit(sound, pow(2.0, semitones / 12.0), volume_scale)


func set_volume(value: float) -> void:
	volume = clampf(value, 0.0, 1.0)
	_save()


func set_enabled(value: bool) -> void:
	enabled = value
	_save()


func toggle() -> bool:
	set_enabled(not enabled)
	if enabled:
		play("ui_confirm")
	return enabled


func _emit(sound: String, pitch: float, volume_scale: float) -> void:
	if not enabled or volume <= 0.001:
		return
	var now := _now()
	if now - float(_last_played.get(sound, -99.0)) < RETRIGGER_GUARD:
		return
	var stream := _stream_for(sound)
	if stream == null:
		return
	_last_played[sound] = now

	var player: AudioStreamPlayer = _players[_next]
	_next = (_next + 1) % _players.size()
	player.stream = stream
	player.pitch_scale = clampf(pitch, 0.2, 4.0)
	player.volume_db = linear_to_db(clampf(volume * volume_scale, 0.0008, 1.0))
	player.play()


## Named _stream_for rather than _get: `_get` is Object's virtual property
## accessor, and redefining it with a different signature stops this script
## and every script that references Sfx from compiling at all.
func _stream_for(sound: String) -> AudioStream:
	if _cache.has(sound):
		return _cache[sound]
	var path := SFX_DIR + sound + ".wav"
	if not ResourceLoader.exists(path):
		push_warning("Sfx: missing sound %s" % path)
		_cache[sound] = null
		return null
	var stream: AudioStream = load(path)
	_cache[sound] = stream
	return stream


func _now() -> float:
	return Time.get_ticks_msec() / 1000.0


func _save() -> void:
	var settings: Dictionary = SaveManager.get_section("settings")
	settings["sfx_volume"] = volume
	settings["sfx_enabled"] = enabled
	SaveManager.set_section("settings", settings)
